### ISSUE TITLE
Implement boost button

### ISSUE THREAD

**Issue by tkellogg** [tkellogg/fossil#3]
There's a button, it just doesn't work

Tasks:
* Create a `POST /toots/{id}/boost` endpoint in `server.py` that forwards the operation to mastodon via `requests.post`.
* Setup the `hx-post` attribute in `app/templates/toot.html`

**Comment by alenachao** [comment]
hey, i'd love to work on this! can you assign it to me?

**Comment by tkellogg** [comment]
assigned. Good luck!

**Comment by alenachao** [comment]
Is an open ai api key required for setup? sorry I should've checked beforehand.

**Comment by tkellogg** [comment]
Sort of, but not really. I integrated [`llm`](https://llm.datasette.io/en/stable/index.html), so I'm I'm accessing models though that. The only reason why you need OpenAI, at this point, is because I hardcoded some strings (pointing to `ada-002` and `gpt-3.5-turbo`. I was going to get a local model fully working tonight; i'm waiting until that pans out to update the documentation around models.

If you're fine with OpenAI (it'll cost you a few cents, that's about it), then it's pretty easy to setup an account and get an API key. Otherwise, I'll see if I can get some local models running tonight.

**Comment by tkellogg** [comment]
Completed by #10
